apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sample-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-dep
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
