---
kind: ReplicationController
apiVersion: v1
metadata:
  name: sample-rc
spec:
  replicas: 2
  selector:
    name: sample
  template:
    metadata:
      name: sample-pod
      labels:
        name: sample
    spec:
      containers:
       - name: sample-container
         image: nginx
         ports:
          - containerPort: 80 
